language: node_js

script:
  - npm test
  - npx eslint src/*.ts*
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
